### ISSUE TITLE
Help with master setup

### ISSUE THREAD

**Issue by alessandro-p** [tmate-io/tmate-master#1]
Hello, 
First of all thank you for the great job and for making it open source. 

I am trying to deploy a self hosted version of tmate-master on Kubernetes and, as for now, I was able to deploy both tmate-websocket-server and tmate-ssh-server, but I really do not find a way to get the tmate-master working. I am getting an error on do_boot: 

```
{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.ArgumentError',message=><<"argument error">>},[{erlang,binary_to_integer,[<<"cjntv">>],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,449}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]},{elixir,eval_forms,4,[{file,"src/elixir.erl"},{line,275}]},{'Elixir.Code',eval_string,3,[{file,"lib/code.ex"},{line,240}]},{'Elixir.Mix.Config','-__import__!/2-fun-0-',2,[{file,"lib/mix/config.ex"},{line,158}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,1948}]}]}}
Unable to configure release!
Crash dump is being written to: erl_crash.dump...init terminating in do_boot ({,[{erlang,binary_to_integer,[],[]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,exprs,5,[{_},{_}]},{elixir,eval_forms,4,[{_},{_}]},{Elixir.Code,e

=INFO REPORT==== 6-Dec-2019::11:20:31.189362 ===
    application: mix
    exited: stopped
    type: temporary
argument error
    :erlang.binary_to_integer("cjntv")
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:449: :erl_eval.expr/5
    (stdlib) erl_eval.erl:126: :erl_eval.exprs/5
    (elixir) src/elixir.erl:275: :elixir.eval_forms/4
    (elixir) lib/code.ex:240: Code.eval_string/3
    (mix) lib/mix/config.ex:158: anonymous fn/2 in Mix.Config.__import__!/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
```

I suppose it could be related with migrations, but I can be wrong. 
In tmate-kube/prod there is a txt file with this content: 

```
# run twice. first time will fail with cannot find migrations
Mix.Task.rerun("ecto.migrate", ["-r", Tmate.Repo, "--migrations-path", "./lib/tmate-0.1.1/priv/repo/migrations"])
```
When should I call this command?

**Comment by nviennot** [comment]
Somehow it's trying to convert the string `"cjntv"` into an int. I think it's assuming that the hostname is going to be of the form `master-1` (stateful set names) but you did a deployment, and its hostname is `master-cjntv`

Use a stateful set for master

**Comment by alessandro-p** [comment]
Thanks! You made my day :) That was exactly the problem. 
Concerning the migration instead? Where am I supposed to run the command inside the txt file?
Thanks again for your time.

**Comment by nviennot** [comment]
`kubectl exec -it sts/master` to get a shell on a master server, then `bin/tmate remote_console` to get an elixir shell, and then run the migration
